name: plotly
version: 1.0.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Interactive, browser-based charting library
homepage: https://github.com/rwl/plotly
environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  js: '>=0.6.1+1 <1.0.0'

dev_dependencies:
  build_runner: '>=1.10.0 <2.0.0'
  build_web_compilers: '>=2.4.0 <3.0.0'


#web:
#  compiler:
#    debug: dartdevc